# Generated by Django 3.1 on 2020-08-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_option',
            name='option',
        ),
        migrations.RemoveField(
            model_name='product_option',
            name='product',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updoad',
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='Categories',
            field=models.ManyToManyField(null=True, to='homePage.Categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='homePage/Image'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_thumbnail',
            field=models.ImageField(default='', null=True, upload_to='homePage/images'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='', null=True, upload_to='homePage/images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('cr', 'Customer'), ('sr', 'Seller'), ('bo', 'Both')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Order_detail',
        ),
        migrations.DeleteModel(
            name='Product_option',
        ),
    ]
