# Generated by Django 3.1 on 2020-08-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_auto_20200826_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Categories',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='homePage.Categories'),
        ),
    ]
