# Generated by Django 3.1 on 2020-08-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_auto_20200826_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='homePage/Image/companies')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='option',
            name='option_thumbnail',
            field=models.ImageField(default='', null=True, upload_to='homePage/images/products/options'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='', null=True, upload_to='homePage/images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ManyToManyField(to='homePage.Companies'),
        ),
    ]
