# Generated by Django 3.1 on 2020-08-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_auto_20200826_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='homePage/Image/categories'),
        ),
    ]
