# Generated by Django 3.1 on 2020-08-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0006_auto_20200826_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pd', 'Pendin'), ('dn', 'Done')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('co', 'COD'), ('ca', 'Card'), ('nb', 'Net Banking')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pd', 'Pendin'), ('dn', 'Done')], max_length=2, null=True),
        ),
    ]
