# Generated by Django 3.1 on 2020-08-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0008_auto_20200826_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pd', 'Pendin'), ('od', 'Out For Delivery'), ('de', 'Delivered')], max_length=2, null=True),
        ),
    ]
