# Generated by Django 3.1 on 2020-08-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0010_auto_20200827_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
