# Generated by Django 3.1 on 2020-08-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0013_auto_20200827_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
