# Generated by Django 3.1 on 2020-08-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0014_auto_20200827_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
