# Generated by Django 3.1 on 2020-08-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0018_auto_20200827_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
    ]
