# Generated by Django 3.1 on 2020-08-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0019_auto_20200827_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
