# Generated by Django 3.1 on 2020-08-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0021_auto_20200831_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ManyToManyField(null=True, to='homePage.UserProfile'),
        ),
    ]
