# Generated by Django 3.1 on 2020-09-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0022_auto_20200831_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ManyToManyField(to='homePage.UserProfile'),
        ),
    ]
